# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python workflow

on:
  - push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get install firefox
        mkdir -p drivers
        wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz
        tar xvf geckodriver-v0.32.2-linux64.tar.gz -C drivers/ && rm geckodriver-v0.32.2-linux64.tar.gz
        python -m pip install selenium
    - name: Run script
      run: python nie.py Castellón AU922353 "JHON JAIRO MURILLO GIRALDO" COLOMBIA 1987 644870178 jhonmurillosam@outlook.com "AUT. DE RESIDENCIA TEMPORAL POR CIRCUNS. EXCEPCIONALES POR ARRAIGO"
